"""create users table

Revision ID: 1998ef9eb340
Revises: 
Create Date: 2026-06-02 15:54:09.598336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1998ef9eb340'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_information')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_Blog_table_id'), table_name='Blog_table')
    op.drop_table('Blog_table')
    op.drop_table('user1')
    op.drop_table('job_post_post_tech_stack')
    op.drop_table('payment_token_failed')
    op.drop_table('menu_store')
    op.drop_table('restaurant')
    op.drop_table('bank_user')
    op.drop_table('wallet')
    op.drop_table('payment_token_success')
    op.drop_table('payment_token')
    op.drop_table('orders')
    op.drop_table('students')
    op.drop_table('menu_session')
    op.drop_table('job_post')
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('ukdu5v5sr43g5bfnji4vb8hg5s3'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'phone')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('ukdu5v5sr43g5bfnji4vb8hg5s3'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_table('job_post',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_desc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('post_profile', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('req_experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('post_id', name=op.f('job_post_pkey'))
    )
    op.create_table('menu_session',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), autoincrement=False, nullable=False),
    sa.Column('current_status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True, precision=6), autoincrement=False, nullable=False),
    sa.Column('order_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('menu_session_pkey'))
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey'))
    )
    op.create_table('orders',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_store_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_store_id'], ['menu_store.id'], name=op.f('fksy9agh7xa9kdxrryt61g4ka07')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk32ql8ubntj5uh44ph9659tiih')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_table('payment_token',
    sa.Column('token_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_mobile', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sender_mobile', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sender_wallet_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['wallet.wallet_id'], name=op.f('fkrbdt0pxn28f4x0foy9gs06t6c')),
    sa.PrimaryKeyConstraint('token_id', name=op.f('payment_token_pkey'))
    )
    op.create_table('payment_token_success',
    sa.Column('token_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_mobile', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sender_mobile', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('settled_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('token_id', name=op.f('payment_token_success_pkey'))
    )
    op.create_table('wallet',
    sa.Column('wallet_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phonenumber', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pin', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('acc_information_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pin_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pin_blocked_until', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acc_information_id'], ['account_information.id'], name=op.f('fkla3i5knlskfe50jbf2m4jbehv')),
    sa.PrimaryKeyConstraint('wallet_id', name=op.f('wallet_pkey')),
    sa.UniqueConstraint('acc_information_id', name=op.f('uk4h8h7qug5ry27n8k1ftongqp0'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('bank_user',
    sa.Column('mobile_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('mobile_number', name=op.f('bank_user_pkey'))
    )
    op.create_table('restaurant',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('restaurant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_pkey')),
    sa.UniqueConstraint('phone', name=op.f('restaurant_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('menu_store',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('orer_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True, precision=6), autoincrement=False, nullable=False),
    sa.Column('order_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('menu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time_limit', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('restaurant_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name=op.f('fkbp0pyeuhw2ukea9nogv9qwvil')),
    sa.PrimaryKeyConstraint('id', name=op.f('menu_store_pkey'))
    )
    op.create_table('payment_token_failed',
    sa.Column('token_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('receiver_mobile', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sender_mobile', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('token_id', name=op.f('payment_token_failed_pkey'))
    )
    op.create_table('job_post_post_tech_stack',
    sa.Column('job_post_post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_tech_stack', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_post_post_id'], ['job_post.post_id'], name=op.f('fkowsxoi2yxj5rgi550qq1skvd4'))
    )
    op.create_table('user1',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('Blog_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Blog_table_pkey'))
    )
    op.create_index(op.f('ix_Blog_table_id'), 'Blog_table', ['id'], unique=False)
    op.create_table('user_session',
    sa.Column('phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('current_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pin_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiver_mobile', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('captcha_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('captcha_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('phone_number', name=op.f('user_session_pkey'))
    )
    op.create_table('account_information',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('debit_card_pin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('debit_card_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('account_information_pkey'))
    )
    # ### end Alembic commands ###
