"""create subject

Revision ID: 615df0db8cd5
Revises: d9bf2235d2f7
Create Date: 2026-06-04 16:23:13.060791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615df0db8cd5'
down_revision: Union[str, Sequence[str], None] = 'd9bf2235d2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('subjects', 'Description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('subjects', 'description')
    # ### end Alembic commands ###
